-
  name: Deploy a web application
  hosts: server
  #vars:
    #db_name: employee_db
    #db_user: db_user
    #db_password: Passw0rd
  
  #tasks:  
    #- include: tasks/deploy_db.yml roles dosyalari kullanmazken direkt ayni dizindeki tasks dan cekmek icin
    #- include: tasks/deploy_web.yml
  roles: #ordering is important
    - python
    - mysql_db
    - flask_web
    
    